# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\holyp\OneDrive\Рабочий стол\asd\qt-project-main\ui\OrderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderWindow(object):
    def setupUi(self, OrderWindow):
        OrderWindow.setObjectName("OrderWindow")
        OrderWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        OrderWindow.resize(976, 598)
        font = QtGui.QFont()
        font.setPointSize(13)
        OrderWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(OrderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 471, 572))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.orderTableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.orderTableWidget.setObjectName("orderTableWidget")
        self.orderTableWidget.setColumnCount(0)
        self.orderTableWidget.setRowCount(0)
        self.gridLayout_4.addWidget(self.orderTableWidget, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.totalLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.totalLabel.setFont(font)
        self.totalLabel.setObjectName("totalLabel")
        self.gridLayout_2.addWidget(self.totalLabel, 2, 0, 1, 1)
        self.orderList = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.orderList.setFont(font)
        self.orderList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.orderList.setIconSize(QtCore.QSize(24, 24))
        self.orderList.setObjectName("orderList")
        self.gridLayout_2.addWidget(self.orderList, 0, 0, 1, 4)
        self.totalSum = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.totalSum.setFont(font)
        self.totalSum.setObjectName("totalSum")
        self.gridLayout_2.addWidget(self.totalSum, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        OrderWindow.setCentralWidget(self.centralwidget)
        self.addCategoryMenu = QtWidgets.QAction(OrderWindow)
        self.addCategoryMenu.setObjectName("addCategoryMenu")
        self.addProductMenu = QtWidgets.QAction(OrderWindow)
        self.addProductMenu.setObjectName("addProductMenu")
        self.exitMenu = QtWidgets.QAction(OrderWindow)
        self.exitMenu.setObjectName("exitMenu")
        self.initTestData = QtWidgets.QAction(OrderWindow)
        self.initTestData.setObjectName("initTestData")

        self.retranslateUi(OrderWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderWindow)

    def retranslateUi(self, OrderWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderWindow.setWindowTitle(_translate("OrderWindow", "Просмотр заказов"))
        self.totalLabel.setText(_translate("OrderWindow", "Итого:"))
        self.totalSum.setText(_translate("OrderWindow", "0"))
        self.addCategoryMenu.setText(_translate("OrderWindow", "Добавить категорию"))
        self.addProductMenu.setText(_translate("OrderWindow", "Добавить блюдо"))
        self.exitMenu.setText(_translate("OrderWindow", "Выход"))
        self.initTestData.setText(_translate("OrderWindow", "Загрузить тестовые данные"))
